---
downloads: ~/.ansible-downloads/

# turn off these features for now
configure_dotfiles: false
configure_terminal: false
configure_osx: false

# configure the Dock via dockutil
configure_dock: false
dockitems_remove:
 - Launchpad
 - TV
 - Podcasts
 - 'App Store'
dockitems_persist:
 - name: "Docker Desktop"
   path: "/Applications/Docker.app/"
   pos: 1

# for security always require this
configure_sudoers: false
sudoers_custom_config: ''

# standard packages for Homebrew
homebrew_installed_packages:
  - autoconf
  - bash-completion
  - git
  - gh
  - gpg
  - pipx
  - readline
  - ssh-copy-id
  - thefuck
  - wget
homebrew_taps:
  - microsoft/git
homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: true
homebrew_cask_apps:
  - 1password-cli
  - docker
  - google-chrome

# don't use these package managers yet
mas_installed_apps: []
mas_email: ""
mas_password: ""
composer_packages: []
gem_packages: []
npm_packages: []
pip_packages: []

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
